export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';
export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const FETCH_CREDIT_CARDS = 'FETCH_CREDIT_CARDS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const OPEN_REGISTRATION_PAGE = 'OPEN_REGISTRATION_PAGE';
export const OPEN_LOGIN_PAGE = 'OPEN_LOGIN_PAGE';
export const LOADING = 'LOADING';